services:
  - type: web
    name: friendprep-ai
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: AI_PROVIDER
        value: huggingface
      - key: HF_TOKEN
        sync: false
      - key: AI_MODEL
        value: "Qwen/Qwen3-4B-Instruct-2507"
      - key: DATABASE_URL
        fromDatabase:
          name: friendprep-ai-db
          property: connectionString
databases:
  - name: friendprep-ai-db
    databaseName: friendprep_ai
    user: friendprep_ai
