# Generated by Django 5.2.17 on 2026-10-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=120)),
                ('target_role', models.CharField(max_length=120)),
                ('experience_level', models.CharField(max_length=80)),
                ('skills', models.TextField()),
                ('resume', models.TextField()),
                ('job_description', models.TextField()),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('completed', 'Completed')], default='setup', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='interview_i_status_9c9a5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('strengths', models.TextField(blank=True, default='')),
                ('weaknesses', models.TextField(blank=True, default='')),
                ('recommended_topics', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interview.interviewsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(default=1)),
                ('question', models.TextField()),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('question_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('practical', 'Practical'), ('follow_up', 'Follow Up')], default='technical', max_length=20)),
                ('answer', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interviewsession')),
            ],
            options={
                'ordering': ['question_number'],
                'indexes': [models.Index(fields=['session', 'question_number'], name='interview_i_session_b25a0f_idx')],
            },
        ),
    ]
